name: GitHub Readme YouTube Cards
on:
  schedule:
    # Todos los viernes a las 12:00 am
    - cron: "0 0 * * FRI"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCKLJBlNT-OpAfXHkNieTowA